### ISSUE TITLE
Excellent and unique book. Would you consider a Bayesian version?

### ISSUE THREAD

**Issue by achamess** [stanlazic/labstats#1]
Hi,
I'm an MD-PhD student at Duke. I've really enjoyed your book for learning the fundamentals of experimental design and analysis as a wet-bench neuroscientist. I'm also interested in the everyday use of Bayesian statistics for bench scientists doing typical experiments (drug treatment, rodent behavior, etc.). I've been reading the books by Kruschke and McElreath, which are great. But they're a bit divorced from the concrete biology scenarios you lay out in the book, which are really helpful for me to understand the material. In the next edition, would you consider having a companion to Chapters 4 and 5 that provides the Bayesian alternative to the classical tests you include in the book?

**Comment by stanlazic** [comment]
Great! Good to hear you're finding it useful. I'm writing another book on Bayesian methods for lab biologists. The first draft should be done by end of 2019. I'll keep you in the loop!

**Comment by achamess** [comment]
@stanlazic That's fantastic news! If you need a very early draft reader (from the student perspective) please keep me in mind. The book you're describing is what I've been waiting for all during grad school. If someone can make Bayesian stats as accessible (practically, not just in concept) to lab biologists, they will gain much more traction.

**Comment by stanlazic** [comment]
Sounds great, many thanks for offering to be a guinea pig :-)

**Comment by achamess** [comment]
Hi. I just wanted to check in to see how the Bayesian book has been going.
